Repository radondb/radon, pull requests merged in 2018-12, with the labels that each got.

#160 makefile: change lint to check
  .gitignore
  makefile
Labels: enhancement

#162 *: fixup gometalinter warnings #161
  .travis.yml
  src/backend/xacheck.go
  src/proxy/query.go
Labels: qa

#164 proxy: fix the unsupport subquery report err #154
  src/proxy/query.go
  src/proxy/query_test.go
Labels: bug

#179 *: add parameter for stream fetch buffer seize #176
  src/config/config.go
  src/ctl/v1/radon.go
  src/ctl/v1/radon_test.go
  src/proxy/execute.go
  src/proxy/proxy.go
  src/proxy/select.go
Labels: feature
